#!/bin/bash
# Function checkLink:
# args: $1 - file
#
# Will loop through all dynamic links for $file, and update each to be relative.
function checkLink {
	#echo "checkLink called with $1 $2"
	local FILE=$1

	#otool -L $FILE

	otool -L $FILE | grep -v 'RawTherapee.app' | grep -v '/usr/lib' | grep -v '/System/' | grep -v "@executable_path" | cut -f 1 -d ' ' | while read X
	do 
		local NAME=`basename "$X"`
		if [ ! -f "RawTherapee.app/Contents/MacOS/lib/$NAME" ]
		then
			#echo "Copy $X to Frameworks"
			cp $X "RawTherapee.app/Contents/MacOS/lib/$NAME"
		
			#Recursively update the linkage of libraries
			checkLink "RawTherapee.app/Contents/MacOS/lib/$NAME"
		fi
	done
}

MACPORTS_PREFIX=/usr/local/rawtherapee
CWD=`pwd`

if [ ! -d release ]; then
	echo "Please run this from the root of the project; i.e. './tools/osx/make-app-bundle'."
	exit
fi

if [ -d RawTherapee.app ]; then
	echo "Removing old RawTherapee.app..."
	rm -rf "RawTherapee.app"
fi
if [ -f release/RawTherapee.dmg ]; then
	echo "Removing old RawTherapee.dmg..."
	rm "release/RawTherapee.dmg"
fi

echo "Making application directory structure..."
mkdir -p "RawTherapee.app/Contents/Resources"
mkdir -p "RawTherapee.app/Contents/MacOS/lib"
mkdir -p "RawTherapee.app/Contents/MacOS/share/mime"

#Copy over non-explicitly linked libraries
echo "Copying libraries from ${MACPORTS_PREFIX}..."
cp -R $MACPORTS_PREFIX/lib/pango RawTherapee.app/Contents/MacOS/lib
cp -R $MACPORTS_PREFIX/lib/gtk-2.0 RawTherapee.app/Contents/MacOS/lib

#Copy over mimes (if a mime is copied, and nobody hears, is it really copied?)
echo "Copying shared files from ${MACPORTS_PREFIX}..."
cp -R /usr/local/rawtherapee/share/mime/* RawTherapee.app/Contents/MacOS/share/mime

#Copy over etc files, and modify as needed
echo "Copying configuration files from ${MACPORTS_PREFIX} and modifying for standalone app bundle..."
cp -R /usr/local/rawtherapee/etc RawTherapee.app/Contents/MacOS
sed -i .bak -e 's/\/usr\/local\/rawtherapee/@executable_path/g' RawTherapee.app/Contents/MacOS/etc/gtk-2.0/gdk-pixbuf.loaders RawTherapee.app/Contents/MacOS/etc/pango/pango.modules
echo -e "[Pango]\nModuleFiles = /tmp/pango.modules" > RawTherapee.app/Contents/MacOS/etc/pango/pangorc


#Copy over the RawTherapee release
echo "Copying RawTherapee release files..."
cp -R release/* RawTherapee.app/Contents/MacOS

#Copy application-specific stuff like icons and startup script
echo "Creating required application bundle files..."
cp tools/osx/Info.plist RawTherapee.app/Contents
cp tools/osx/RawTherapee.icns RawTherapee.app/Contents/Resources
cp tools/osx/rtstart RawTherapee.app/Contents/MacOS

#Copy and relink the explicitly defined libraries
echo "Recursively copying libraries referenced by rt..."
checkLink "RawTherapee.app/Contents/MacOS/rt"

#Make a .dmg for distribution and delete the .app
echo "Creating distribution .dmg..."
hdiutil create -srcdir RawTherapee.app release/RawTherapee.dmg
echo "Cleaning up..."
rm -rf RawTherapee.app

echo "All done!"
