#!/bin/bash
# Function checkLink:
# args: $1 - file
#
# Will loop through all dynamic links for $file, and update each to be relative.
function checkLink {
	#echo "checkLink called with $1 $2"
	local FILE=$1

	#otool -L $FILE

	otool -L $FILE | grep -v 'RawTherapee.app' | grep -v '/usr/lib' | grep -v '/System/' | grep -v "@executable_path" | cut -f 1 -d ' ' | while read X
	do 
		local NAME=`basename "$X"`
		if [ ! -f "RawTherapee.app/Contents/MacOS/lib/$NAME" ]
		then
			#echo "Copy $X to Frameworks"
			cp $X "RawTherapee.app/Contents/MacOS/lib/$NAME"
		
			#Recursively update the linkage of libraries
			checkLink "RawTherapee.app/Contents/MacOS/lib/$NAME"
		fi
	done
}

MACPORTS_PREFIX=/usr/local/rawtherapee
CWD=`pwd`

if [ ! -d release ]; then
	echo "Please run this from the root of the project; i.e. './tools/osx/make-app-bundle'."
	exit
fi

rm -rf "RawTherapee.app"
mkdir -p "RawTherapee.app/Contents/Resources"
mkdir -p "RawTherapee.app/Contents/MacOS/lib"
mkdir -p "RawTherapee.app/Contents/MacOS/share/mime"

#Copy over non-explicitly linked libraries
cp -R $MACPORTS_PREFIX/lib/pango RawTherapee.app/Contents/MacOS/lib
cp -R $MACPORTS_PREFIX/lib/gtk-2.0 RawTherapee.app/Contents/MacOS/lib

#Copy over mimes (if a mime is copied, and nobody hears, is it really copied?)
cp -R /usr/local/rawtherapee/share/mime/* RawTherapee.app/Contents/MacOS/share/mime

#Copy over etc files, and modify as needed
cp -R /usr/local/rawtherapee/etc RawTherapee.app/Contents/MacOS
sed -i .bak -e 's/\/usr\/local\/rawtherapee/\/Users\/wyatt\/Documents\/Programming\/RawTherapee\/rawtherapee.fork\/RawTherapee.app\/Contents\/MacOS/g' RawTherapee.app/Contents/MacOS/etc/gtk-2.0/gdk-pixbuf.loaders RawTherapee.app/Contents/MacOS/etc/pango/pango*

#Copy over the RawTherapee release
cp -R release/* RawTherapee.app/Contents/MacOS

#Copy application-specific stuff like icons and startup script
cp tools/osx/Info.plist RawTherapee.app/Contents
cp tools/osx/RawTherapee.icns RawTherapee.app/Contents/Resources
cp tools/osx/rtstart RawTherapee.app/Contents/MacOS

#Copy and relink the explicitly defined libraries
checkLink "RawTherapee.app/Contents/MacOS/rt"
